alias genLex="dotnet ../fsharp/FsLexYacc.11.3.0/build/fslex/net6.0/fslex.dll --unicode CLex.fsl"
alias genPar="dotnet ../fsharp/FsLexYacc.11.3.0/build/fsyacc/net6.0/fsyacc.dll --module CPar CPar.fsy"
alias runInterp="dotnet fsi -r ../fsharp/FsLexYacc.Runtime.11.3.0/lib/netstandard2.0/FsLexYacc.Runtime.dll Util.fs Absyn.fs CPar.fs CLex.fs Parse.fs Interp.fs ParseAndRun.fs"
alias runComp="dotnet fsi -r ../fsharp/FsLexYacc.Runtime.11.3.0/lib/netstandard2.0/FsLexYacc.Runtime.dll Util.fs Absyn.fs CPar.fs CLex.fs Parse.fs Machine.fs Comp.fs ParseAndComp.fs"
alias runContComp="dotnet fsi -r ../fsharp/FsLexYacc.Runtime.11.3.0/lib/netstandard2.0/FsLexYacc.Runtime.dll Util.fs Absyn.fs CPar.fs CLex.fs Parse.fs Machine.fs Contcomp.fs ParseAndContcomp.fs"
alias clean="rm ./CLex.fs ./CLex.fsi ./CPar.fs ./CPar.fsi"